<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpgzxgx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpgzxgx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSpgzxgx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSpgzxgx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSpgzxgx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Spgzxgx',
    'container.build_id' => '3cb9f836',
    'container.build_time' => 1542740817,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpgzxgx');
